### PR TITLE
fixes #9

### LINKED ISSUE #9: Column widths for Publication page
There is awkward wrapping of text in some of the columns. This is most annoying now for the journal citation since PRC has passed issue 99, but some of the titles are quite long and spread over many lines. Can the columns be made wider? There is quite a bit of white space on the sides which could be reduced. I guess this is something in the css but I cannot figure it out. Thanks!

### PR DESCRIPTION
**Pull request by katieannemills**
Per your request, @AdamGarnsworthy. Have a look before merging at the result previewed at https://billmills.github.io/griffin-website/publications.html, and of course you can adjust the margins further as desired.

### CODE REVIEW

**Comment by katieannemills** [comment]
We could also squish the authors column a bit to make more room, if the wrap is still too much.

**Comment by AdamGarnsworthy** [comment]
@BillMills Thanks for doing this, this row margin change is a good one. Can you also show me how to squish the authors column as you suggest. Thanks.

**Comment by katieannemills** [comment]
@AdamGarnsworthy columns rebalanced in 5898398. In general, bootstrap expects column widths to add up to 12; I did 5-2-3-2 to give titles the most room, but feel free to tweak as desired. I also took the liberty of applying a similar correction to the Thesis page, let me know any comments there.

**Comment by AdamGarnsworthy** [comment]
Great, everything is much clearer to me now. Thanks very much!

**Comment by katieannemills** [comment]
A pleasure and a privilege as always, let me know if there's anything else I can do.

**Pull request merged**
